# Generated by Django 5.1.5 on 2025-02-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0002_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
